import { getRandomKey } from "../utils/CommonUtils";

export const CONTACT_LIST: Contact[] = [
  {
    contact_id: getRandomKey(),
    contact_name: "Ronica Dablin",
    phone: "719-119-8057",
    address: "2 Prairieview Trail",
    description:
      "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
    company: "Oyoloo",
    city: "Haninge",
    state: "Stockholm",
    country: "Sweden",
  },
  {
    contact_id: getRandomKey(),
    contact_name: "Aleksandr Sandyford",
    phone: "513-113-3703",
    address: "47340 Lindbergh Pass",
    description:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    company: "Vimbo",
    city: "Ladozhskaya",
    state: null,
    country: "Russia",
  },
  {
    contact_id: getRandomKey(),
    contact_name: "Annemarie Menilove",
    phone: "937-523-2413",
    address: "0214 Union Road",
    description:
      "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.",
    company: "Realcube",
    city: "Heqiao",
    state: null,
    country: "China",
  },
  {
    contact_id: getRandomKey(),
    contact_name: "Ursala Schinetti",
    phone: "854-914-1570",
    address: "095 Moland Circle",
    description:
      "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    company: "Jetpulse",
    city: "Zhangyelu",
    state: null,
    country: "China",
  },
  {
    contact_id: getRandomKey(),
    contact_name: "Florina Dafter",
    phone: "815-961-0066",
    address: "0 1st Center",
    description:
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    company: "Thoughtsphere",
    city: "Las Palmas",
    state: "Veracruz Llave",
    country: "Mexico",
  },
  {
    contact_id: getRandomKey(),
    contact_name: "Khalil Jamison",
    phone: "706-755-0838",
    address: "9108 Gulseth Lane",
    description:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    company: "Roodel",
    city: "Langgapayung",
    state: null,
    country: "Indonesia",
  },
  {
    contact_id: getRandomKey(),
    contact_name: "Alden Dethloff",
    phone: "412-399-2310",
    address: "21 Farwell Parkway",
    description: "In congue. Etiam justo. Etiam pretium iaculis justo.",
    company: "Dabshots",
    city: "Kučevo",
    state: null,
    country: "Serbia",
  },
  {
    contact_id: getRandomKey(),
    contact_name: "Yvon Calverley",
    phone: "237-376-6600",
    address: "307 Pankratz Plaza",
    description:
      "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    company: "Meejo",
    city: "Muldersdriseloop",
    state: null,
    country: "South Africa",
  },
  {
    contact_id: getRandomKey(),
    contact_name: "Salomone Whimper",
    phone: "270-391-6696",
    address: "0 Myrtle Place",
    description:
      "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    company: "Riffpath",
    city: "Calceta",
    state: null,
    country: "Ecuador",
  },
  {
    contact_id: getRandomKey(),
    contact_name: "Garland Fellow",
    phone: "193-436-4380",
    address: "4 Vidon Terrace",
    description:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    company: "Kaymbo",
    city: "Dengyue",
    state: null,
    country: "China",
  },
  {
    contact_id: getRandomKey(),
    contact_name: "Monro Martijn",
    phone: "337-622-8128",
    address: "62936 Butterfield Lane",
    description:
      "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    company: "Yadel",
    city: "Roermond",
    state: "Provincie Limburg",
    country: "Netherlands",
  },
  {
    contact_id: getRandomKey(),
    contact_name: "Rafi Volcker",
    phone: "304-307-1604",
    address: "18669 Moulton Place",
    description:
      "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    company: "Linkbuzz",
    city: "Zhengcun",
    state: null,
    country: "China",
  },
  {
    contact_id: getRandomKey(),
    contact_name: "Bambie Heritege",
    phone: "788-724-3177",
    address: "9 Monument Street",
    description:
      "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    company: "Divanoodle",
    city: "Yingtan",
    state: null,
    country: "China",
  },
  {
    contact_id: getRandomKey(),
    contact_name: "Cash MacKeeg",
    phone: "477-539-7037",
    address: "3187 Gale Point",
    description:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    company: "Agimba",
    city: "Besançon",
    state: "Franche-Comté",
    country: "France",
  },
  {
    contact_id: getRandomKey(),
    contact_name: "Boris MacGiffin",
    phone: "125-646-4956",
    address: "47074 Lighthouse Bay Center",
    description:
      "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    company: "Meejo",
    city: "Naebugis",
    state: null,
    country: "Indonesia",
  },
  {
    contact_id: getRandomKey(),
    contact_name: "Amabelle Yewen",
    phone: "662-269-3070",
    address: "72 New Castle Road",
    description:
      "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    company: "Myworks",
    city: "Guáimaro",
    state: null,
    country: "Cuba",
  },
  {
    contact_id: getRandomKey(),
    contact_name: "Carroll Gerrit",
    phone: "310-610-6585",
    address: "93 Westend Hill",
    description:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    company: "Jaxworks",
    city: "La Calera",
    state: null,
    country: "Argentina",
  },
  {
    contact_id: getRandomKey(),
    contact_name: "Huey Polhill",
    phone: "647-133-6464",
    address: "7348 Bunting Terrace",
    description:
      "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    company: "Gabspot",
    city: "Reitoca",
    state: null,
    country: "Honduras",
  },
  {
    contact_id: getRandomKey(),
    contact_name: "Glyn Torrans",
    phone: "515-695-4095",
    address: "7269 Clove Way",
    description:
      "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    company: "Browsetype",
    city: "Yushugou",
    state: null,
    country: "China",
  },
  {
    contact_id: getRandomKey(),
    contact_name: "Madelaine Durham",
    phone: "218-327-6629",
    address: "26600 Clyde Gallagher Lane",
    description:
      "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    company: "Zoomdog",
    city: "Bazar-Korgon",
    state: null,
    country: "Kyrgyzstan",
  },
];
